# PostgtreSQL 9.4
#
# VERSION      9.4

FROM lindep/geo_base
MAINTAINER Pieter Linde

#RUN apt-get update && apt-get -y install wget
COPY apt/sources.list.d/pgdg.list /etc/apt/sources.list.d/pgdg.list
COPY apt/sources.list /etc/apt/sources.list

#RUN apt-get update && apt-get install -y build-essential sqlite3 libsqlite3-dev


RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
RUN apt-get update && apt-get install -y postgresql-9.4 \
	postgresql-contrib-9.4 \
	postgresql-9.4-postgis-2.1 \
	postgresql-client-9.4 \
#	libgdal-dev \
#	libgdal-perl \
#	python-gdal \
#	python-geolinks \
#	libspatialite-dev \
#	inotify-tools \
	&& rm -rf /var/lib/apt/lists/*

COPY geoTools /tmp/geoTools
RUN cd /tmp/geoTools/geos-3.4.2 && make clean && ./configure && make && make install
RUN ldconfig
RUN cd /tmp/geoTools/proj-4.9.1 && make clean && ./configure && make && make install
RUN ldconfig
RUN cd /tmp/geoTools/gdal-1.11.2 && make clean && ./configure --with-sqlite3=yes --with-spatialite=yes && make && make install
RUN ldconfig


ADD ./scripts/postgres.sh /var/lib/postgresql/postgres.sh
RUN chown postgres:postgres /var/lib/postgresql/postgres.sh
RUN chmod +x /var/lib/postgresql/postgres.sh

USER postgres

# Initial default user/pass and schema
ENV USER postgres
ENV PASSWORD postgres
ENV SCHEMA postgres
ENV POSTGIS false

RUN echo "listen_addresses='*'" >> /etc/postgresql/9.4/main/postgresql.conf
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.4/main/pg_hba.conf

VOLUME	["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

RUN touch /var/tmp/firstrun

EXPOSE 5432
CMD ["/var/lib/postgresql/postgres.sh"]



